INSERT INTO `candidato`(`calificacion_psicologica`, `correo`, `dui`,`estado_civil`,`fecha_nacimiento`,`habilidades`,`licencia_conducir`,`nit`,`nombre`,`telefono`) VALUES (8,'alonso@gmail.com' ,'02307645-8', 'casado/a','1993/12/03','Js, HTML, CSS, Python, Java, Docker, Kubernetes','23454376788765','3464-538655-267-8','Moran Aguilar Alonso Vladimir','2347-6653');
INSERT INTO `candidato`(`calificacion_psicologica`, `correo`, `dui`,`estado_civil`,`fecha_nacimiento`,`habilidades`,`licencia_conducir`,`nit`,`nombre`,`telefono`) VALUES (9,'juan@gmail.com' ,'05687934-8', 'soltero/a','1993/12/03','RPG, HTML, CSS, Python, Java, Docker, Kubernetes','45327689096543','3464-538655-267-8','Acevedo Manríquez Juan Enrique','1234-8934');
INSERT INTO `candidato`(`calificacion_psicologica`, `correo`, `dui`,`estado_civil`,`fecha_nacimiento`,`habilidades`,`licencia_conducir`,`nit`,`nombre`,`telefono`) VALUES (8,'antonio@gmail.com' ,'02307645-8', 'casado/a','1993/12/03','SQL, MongoDB, CI/CD, Python, Java, Docker, Kubernetes','23454376788765','3464-538655-267-8','Palomeque Armando Jose Antonio','7834-2367');
INSERT INTO `candidato`(`calificacion_psicologica`, `correo`, `dui`,`estado_civil`,`fecha_nacimiento`,`habilidades`,`licencia_conducir`,`nit`,`nombre`,`telefono`) VALUES (7,'oscar@gmail.com' ,'02307645-8', 'soltero/a','1993/12/03','Typescript, Angular, Python, Java, Docker, Kubernetes','45327689096543','3464-538655-267-8','Alvarado Mendoza Oscar Roberto','9934-3322');
INSERT INTO `candidato`(`calificacion_psicologica`, `correo`, `dui`,`estado_civil`,`fecha_nacimiento`,`habilidades`,`licencia_conducir`,`nit`,`nombre`,`telefono`) VALUES (8,'marta@gmail.com' ,'02307645-8', 'soltero/a','1993/12/03','NodeJs, Python, Java, Docker, Kubernetes','23454376788765','3464-538655-267-8','Anzures Valladares Marta Abigail','3934-8944');
INSERT INTO `candidato`(`calificacion_psicologica`, `correo`, `dui`,`estado_civil`,`fecha_nacimiento`,`habilidades`,`licencia_conducir`,`nit`,`nombre`,`telefono`) VALUES (8,'nicole@gmail.com' ,'02307645-8', 'soltero/a','1993/12/03','TensorFlow, Python, CI/CD, Docker, Kubernetes','45327689096543','3464-538655-267-8','Valladares Ruiz Alicia Nicole','2254-0965');
INSERT INTO `candidato`(`calificacion_psicologica`, `correo`, `dui`,`estado_civil`,`fecha_nacimiento`,`habilidades`,`licencia_conducir`,`nit`,`nombre`,`telefono`) VALUES (10,'pedro@gmail.com' ,'02307645-8', 'casado/a','1993/12/03','AWS, NodeJs, React, Python, Docker, Kubernetes','23454376788765','3464-538655-267-8','Rosales Perez Pedro David','7899-2377');
INSERT INTO `candidato`(`calificacion_psicologica`, `correo`, `dui`,`estado_civil`,`fecha_nacimiento`,`habilidades`,`licencia_conducir`,`nit`,`nombre`,`telefono`) VALUES (8,'maria@gmail.com' ,'02307645-8', 'casado/a','1993/12/03','Azure, DevOps, Linux, CI/CD, Docker, Kubernetes','45327689096543','3464-538655-267-8','Canales Mejia Maria Alejandra','7684-2376');
INSERT INTO `candidato`(`calificacion_psicologica`, `correo`, `dui`,`estado_civil`,`fecha_nacimiento`,`habilidades`,`licencia_conducir`,`nit`,`nombre`,`telefono`) VALUES (10,'ana@gmail.com' ,'02307645-8', 'soltero/a','1993/12/03','Linux, HTML, CSS, Python, Java, Docker, Kubernetes','23454376788765','3464-538655-267-8','Romero Delgado Ana Paola','4476-7689');
INSERT INTO `candidato`(`calificacion_psicologica`, `correo`, `dui`,`estado_civil`,`fecha_nacimiento`,`habilidades`,`licencia_conducir`,`nit`,`nombre`,`telefono`) VALUES (6,'mari@gmail.com' ,'02307645-8', 'soltero/a','1993/12/03','ObjectiveC, Swift, Mobile, ReactNative, Java, Kotlin','45327689096543','3464-538655-267-8','Rosario Posas Mari Adela','9945-0945');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('ANALISTA PROGRAMADOR JAVA','2022/11/02','N',3,'Desarrollar nuvos sistemas y realizar mantenimientoa los ya existentes trabajando con Java y .Net','1. conocimientos de .NET, C# y Java para la administración de página Web e Ebanking ,2. conocimientos de PLSQL para crear Script en reportes de BD ORACLE.');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('ANALISTA PROGRAMADOR JAVA','2022/11/02','N',3,'- Modificación y mantenimiento de sistemas en plataforma y PHP.,- Gestionar el buen funcionamiento de los sistemas de información web,- Gestionar el buen funcionamiento de sitios web empresariales.','- Graduado o egresado de Ingeniería en sistemas o carreras a fines.,- Experiencia mínima 1 año en cargos similares.,- Desarrollador Web en aplicaciones de consultas y formularios de sistemas de información.');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('ANALISTA PROGRAMADOR JAVA','2022/11/02','N',3,'- Planeación de desarrollo de sistemas en cuanto a modificaciones y mejoras, así como nuevos sistemas web.,- Servicios de atención a los usuarios en las necesidades de sistemas de información.','- Ingeniería del software con estrategia BPM.,- Básico de metodologías de desarrollo agiles (RUP / Agile / SCRUM).,- Lenguajes de consulta de consulta de Base de Datos (TSQL, PL/SQL).');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('ANALISTA PROGRAMADOR JAVA','2022/11/02','N',3,'- Documentación de manuales, video manuales de sistemas de información.,- Capacitación de uso de sistemas.,- Apoyo en desarrollo de sistemas web.','- Lenguaje de Programación PHP, JavaScript, Java, VB.net, C#.net.,-Frameworks, angular, Vuejs,- Herramientas GIT');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('ANALISTA PROGRAMADOR JAVA','2022/11/02','N',3,'- Apoyo en la implementación de sistemas web desarrollados.','- Herramientas de documentación de sistemas, manuales técnicos de usuarios.,- Desarrollo de Android, iOs (Indispensable)');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('ANALISTA PROGRAMADOR JAVA','2022/11/02','N',3,'- Documentación de manuales, video manuales de sistemas de información.,- Capacitación de uso de sistemas.','- Dominio de los paquetes...,* Vs Code, Visual Studio Code,* FTP (Filezilla, FTP Voyager, etc.)');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('ANALISTA PROGRAMADOR JAVA','2022/11/02','N',3,'- Programación orientada a Objetos ,arquitectura de aplicaciones, estándares de codificación y programación así como versionamiento de fuentes.','- Egresado o graduado de Ingeniería en sistemas o carreras afines.,- Conocimiento intermedio/avanzado de JAVA y Frontend Angular.,- Conocimientos sólidos de base de datos.');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('ANALISTA PROGRAMADOR JAVA','2022/11/02','N',3,'Planeación de desarrollo de sistemas en cuanto a modificaciones y mejoras','Graduado de Ing En Sistemas o carreras afines,Experiencia de 3 años en adelante,Experiencia con desarrollo Microservicios en Java SpringBoot/Spring');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('ANALISTA PROGRAMADOR JAVA','2022/11/02','N',3,'Apoyo en la implementación de sistemas web desarrollados.','Experiencia con bases de datos relacionales (SQL Server, Sybase u Oracle),Uso de Contenedores (Docker, Kubernetes),Versionamiento con Git (experiencia con Github, Gitlab, y/o Bitbucket)');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('FRONTEND SENIOR REACT JS','2022/11/02','N',3,'optimizar las aplicaciones para obtener la máxima velocidad,optimizar las aplicaciones para obtener la máxima escalabilidad,diseñar nuevas funciones o mantener las antiguas','buen conocimiento y experiencia práctica de herramientas de prueba como Webpack, Jasmine, Karma, etc.,buen conocimiento de las herramientas de versionado de código, como Git, Mercurial o SVN');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('PROGRAMADOR ORACLE','2022/11/02','N',3,'Estamos buscando Programadores Oracle que quieran formar parte de nuestro equipo','Experiencia con Lenguaje de programación Oracle PL-SQL,Experiencia en el desarrollo de aplicaciones con Oracle forms and Reports 11g.,Conocimientos de Lenguaje Java y Spring Framework');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('DEVOPS ENGINEER','2022/11/02','N',3,'Platform & Infrastructure Implementation,Work in an intensive project-oriented environment and maintain ownership of overall deliverable consistency and quality.','Bachelor’s degree in Computer Science or equivalent degree or experience,3-5 years of Linux Administration experience, preferably Ubuntu, including patch management');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('DATA SCIENCE DATA ENGINEER','2022/11/02','N',3,'- Interview other Data Scientists and Data engineers to vet their technical abilities.,- Input data from those interviews into the product and help develop a predictive, fair, and enjoyable solution.','- 5+ years of experience working as a developer.,- 3+ years of experience working as a Data Scientist / Data Engineer.');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('SALES AGENT REPRESENTATIVE','2022/11/02','N',3,'- Use a customer-focused, consultative sales process to educate customers on energy product offerings,- Respond to inbound phone calls in a timely, efficient and professional manner','- One-year customer service.,- Previous call center back experience.,- High School diploma or equivalent required.');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('FRONTEND SENIOR REACT JS','2022/11/02','N',3,'obtener continuamente información de los usuarios, clientes y colegas,supervisar el rendimiento de la aplicación, vigilar las caídas de tráfico relacionadas con problemas de usabilidad del sitio y rectificar cualquier problema','un alto nivel de experiencia con diseños de interfaz de usuario, SASS, LESS, Bootstrap y el sistema CSS GRID,sólida experiencia en el uso de una API REST compleja desde el lado del cliente');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('DEVOPS ENGINEER','2022/11/02','N',3,'Fault finding, analysis, and logging information for reporting performance exceptions.,Proactively monitoring system performance and capacity planning.','Good understanding of Networking in a TCP/IP and SIP environment is required,Working knowledge of basic networking skills such as switching, and routing, IP addressing');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('SALES AGENT REPRESENTATIVE','2022/11/02','N',3,'- Maintain energy knowledge features and product line ,- Convert a % of calls intro sales/enrollments (% TBD)','- Ability to work independently.,- Ability to read, write, speak and understand the English language in a business environment.');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('FRONTEND SENIOR REACT JS','2022/11/02','N',3,'redactar documentos y guías de requisitos funcionales,crear maquetas y prototipos de calidad, garantizando unos estándares gráficos de alta calidad y la coherencia de la marca,convertir los diseños UI/UX en prototipos, creando excelentes interacciones a partir de los diseños','experiencia significativa en la depuración mediante herramientas basadas en JavaScript como Chrome Developer Console,Alguna exposición a la integración continua / tubería de entrega para la nube, incluyendo Jenkins, SonarQube, Docker, etc.');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('DATA SCIENCE DATA ENGINEER','2022/11/02','N',3,'- Work together with developers, tech leads, and solution architects to build applications.,- Improve existing structures by adding new functionalities or proposing technological updates so that as a result, the impact of your contribution is significant in the core of each business.','- Proficient with analysis, troubleshooting, and problem-solving.,- Hands-on experience with managing data loads and data quality.,- Advanced English level.');
INSERT INTO `proceso`(`titulo`,`apertura`, `closed`, `duracion_meses`,`funciones`,`requerimientos`) VALUES ('DEVOPS ENGINEER','2022/11/02','N',3,'Deploy and maintain complex voice (VOIP) infrastructure components, and automated approaches for identifying and fixing voice quality issues.,Participate with Engineering teams on the design and architecture of voice/video services, optimizing the quality.','Strong familiarity with a wide array of open-source applications and tools, for example, Apache, NGINX, MySQL, Node, Services, Tomcat, PHP, NTP, collected, etc…');
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',1,1);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',1,2);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',1,3);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',1,4);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',2,5);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',2,6);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',2,7);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',2,8);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',3,9);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',3,10);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',3,1);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',3,2);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',4,3);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',4,4);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',4,5);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',4,6);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',5,7);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',5,8);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',5,9);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',5,10);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',6,1);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',6,2);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',6,3);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',6,4);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',7,5);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',7,6);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',7,7);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',7,8);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',8,9);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',8,10);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',8,1);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',8,2);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',9,3);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',9,4);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',9,5);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',9,6);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',10,7);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',10,8);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',10,9);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',10,10);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',11,1);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',11,2);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',11,3);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',11,4);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',12,5);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',12,6);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',12,7);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',12,8);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',13,9);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',13,10);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',13,1);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',13,2);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',14,3);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',14,4);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',14,5);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',14,6);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',15,7);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',15,8);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',15,9);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',15,10);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',16,1);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',16,2);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',16,3);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',16,4);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',17,5);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',17,6);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',17,7);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',17,8);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',18,9);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',18,10);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',18,1);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',18,2);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',19,3);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',19,4);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',19,5);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',19,6);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',20,7);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',20,8);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',20,9);
INSERT INTO `aplicacion`(`aceptada`,`id_proceso`, `id_candidato`) VALUES ('N',20,10);